apiVersion: v1.1
resources:
  - name: gradle_jenkins_acme_results
    type: PropertyBag
    configuration:
      passing: 0
      failing: 0
pipelines:
  - name: ACME_gradlesvc_Jenkins
    steps:
    - name: gradlesvc_build
      type: Jenkins
      configuration:
       jenkinsJobName: gradle-app-acme
       integrations: 
        - name: jenkinsUnified
       outputResources:   
        - name: gradle_jenkins_acme_results
    - name: Validate_Tests
      type: Bash
      configuration:
              inputResources:
              - name: gradle_jenkins_acme_results
              outputResources:
              - name: gosvc_build_info        
      execution:
        onSuccess:
                - "echo passing: ${res_gradle_jenkins_acme_results_passing}"

          
