apiVersion: v1.1
resources:
  - name: gradle_jenkins_fis_results
    type: PropertyBag
    configuration:
      passing: 0
      failing: 0
pipelines:
  - name: FIS_execute_jenkins_job
    steps:
    - name: Jenkins_LoanCalculator
      type: Jenkins
      configuration:
       jenkinsJobName: gradle-app-fis
       integrations: 
        - name: demo_test_JenkinsServer
       outputResources:   
        - name: gradle_jenkins_fis_results
        - name: jenkins_job_build_info
    - name: Validation
      type: Bash
      configuration:
              inputResources:
              - name: gradle_jenkins_fis_results
              - name: jenkins_job_build_info
      execution:
        onSuccess:
                - "echo passing: ${res_gradle_jenkins_fis_results_passing}"

          
