apiVersion: v1.1
resources:
  - name: release_bundle_fis
    type: ReleaseBundle
    configuration:
      sourceDistribution: Distribution
      name: demo_rb_fis
      version: v1.0.0
  - name: signed_bundle_fis
    type: ReleaseBundle
    configuration:
      sourceDistribution: Distribution
      name: demo_rb_fis
      version: v1.0.0
  - name: jenkins_job_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory:    ArtifactoryUnified
      buildName:            gradle-app-fis 
      buildNumber:          1 
      externalCI:           demo_test_JenkinsServer
  - name: distribution_rules_fis
    type: DistributionRule
    configuration:
      sourceDistribution: Distribution
      serviceName: Edge*
      siteName: Edge*
      cityName: '*'
      countryCodes:
        - '*'
pipelines:      
- name: FIS_demo_release_mgmt
  steps:
  - name: bundle
    type: CreateReleaseBundle
    configuration:
      releaseBundleName: demo_rb_fis
      releaseBundleVersion: 'v1.0.${run_number}'
      dryRun: false
      sign: false
      description: some random test description
      inputResources:
        - name: gosvc_promoted_build_info
          trigger: false
        - name: appl_promoted_build_info_fis
          trigger: false
        - name: jenkins_job_build_info
          trigger: false
      outputResources:
        - name: release_bundle_fis
      releaseNotes:
        syntax: markdown
        content: |
          ## Heading
            * Bullet
            * Points
  - name: sign
    type: SignReleaseBundle
    configuration:
      inputResources:
        - name: release_bundle_fis
      outputResources:
        - name: signed_bundle_fis
  - name: distribute
    type: DistributeReleaseBundle
    configuration:
      dryRun: false
      inputResources:
        - name: signed_bundle_fis
        - name: distribution_rules_fis
